/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

#include "main.h"

void p2() {
    cout << "Each new term in the Fibonacci sequence is generated by adding the\n"
            "previous two terms. By starting with 1 and 2, the first 10 terms will be:\n"
            "\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n"
            "By considering the terms in the Fibonacci sequence whose values do not\n"
            "exceed four million, find the sum of the even - valued terms.\n\n";

    //1. set up vector and other variables
    vector<int> fib;
    int total = 0;

    //2. assign the first two values of the Fibonacci sequence (1, 1)
    //   Also note that the first two values are odd so they are not added to the total
    fib.push_back(1);
    fib.push_back(1);

    //3. using a for loop continuously create the sequence until the value of
    //   of one term exceeds 4 million
    for (int x = 1; (fib[x] + fib[x - 1]) < 4000000; x++) {
        fib.push_back(fib[x] + fib[x - 1]);

        //4. Check if the Fibonacci number is even to add to the total
        if (fib[x + 1] % 2 == 0) {
            total += fib[x + 1];
        }
    }

    //4. print out result
    cout << "The total is " << total << endl;
    
    return;
}